# Generated by Django 5.1.1 on 2024-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
